# Action to setup a workspace thanks to repo tool
name: repo-checkout
description: Use repo tool to checkout a workspace composed of several projects
inputs:
    url:
        description: URL to repo manifest repository
        required: true
    manifest:
        description: Name of the manifest file to be used
        required: false
        default: manifest.xml
    branch:
        description: Branch to use on the manifest repository
        required: false
    group:
        description: Name of the project group to be checked out
        required: false
    env:
        description: List (NAME=VALUE,NAME2=VALUE) of env variables to be set
        required: false
runs:
    using: docker
    image: docker://dynod/repo-checkout-action:1.3.2
    args:
        - ${{ inputs.url }}
        - ${{ inputs.manifest }}
        - ${{ inputs.branch }}
        - ${{ inputs.group }}
        - ${{ inputs.env }}
